index.js
package.json

Update stylelint to v7.3.1 and add new rules.

Update to stylelint 7.3.1

---

index.js

Adding rest of stylelint rules
Issue: #3

Rules addition #3

---

index.js

Removed rule: `media-feature-no-missing-punctuation` is deprecated

---

index.js

Was added in #5 without discussion.

Remove shorthand-property-no-redundant-values

---

index.js
package.json

Upgrade to stylelint 7.12

---

index.js

Change rule: `block-opening-brace-space-before` from `always-single-line` to `always`

---

index.js

Adding rule and ignoring on 'after-comment' &
'inside-single-line-block'.
Fixes #73

New rule 'declaration-empty-line-before', set to 'never'

---

index.js

Fixing one instance of wrong order.

Hygiene: Reoder rules alphabetically

---

README.md

README: Encourage naming config files .stylelintrc.json, with a tab

---

README.md
grade-a.json
grade-c.json
package-lock.json
package.json

Create Grade A/C presets for plugin/no-unsupported-browser-features

---

CHANGELOG.md
package-lock.json
package.json

- Require stylelint 13.8.0, up from 13.7.0
- Release 0.10.3

Release 0.10.3

---

grade-a.json
grade-c.json

As per https://www.mediawiki.org/w/index.php?diff=4468318

Grade A/C: Bump MediaWiki browser versions

---

package-lock.json
package.json
support-basic.js
support-modern.js

This should be a no-op change.

Get browsers lists from browserslist-config-wikimedia

---

index.js
package.json
rules/no-at-import-css.js
test/fixtures/default/invalid.css
test/fixtures/default/invalid.less
test/fixtures/default/valid.less

* Disallow @import outside of LESS files
* Disallow @import's that aren't handled by the LESS compiler
Fixes #134

Disallow non-LESS @import at-rules

---

package.json
support-basic-rules.js
support-basic.json
support-modern-rules.js
support-modern.json
test/fixtures/basic/.stylelintrc.json
test/fixtures/modern/.stylelintrc.json
test/index.js

- Tests: Test mediawiki ruleset
- Tests: Test support-basic & support-modern

Test other rulesets

---

index.js
mediawiki.js
package-lock.json
package.json
support-basic-rules.js
support-modern-rules.js
test/fixtures/basic/valid.vue
test/fixtures/default/.stylelintrc.json
test/fixtures/default/valid.vue
test/fixtures/mediawiki/valid.vue
test/fixtures/modern/valid.vue
test/index.js

Thanks, stylelint 14, this is exactly what everyone wanted from you.
Fixes #193.

Add back support for linting .vue files

---

CHANGELOG.md
package-lock.json
package.json

Release 0.14.0

---

package-lock.json
package.json
test/fixtures/modern/invalid.css

Also add --report-needless-disables to test runner as not
all fixtures inherit from core rules (index.js).

modern: Update browserslist-config-wikimedia to 0.5.0

---

package-lock.json
package.json

* Upgrade browserslist-config-wikimedia from 0.5.0 to 0.6.1
* Upgrade postcss-html from 1.5.0 to 1.6.0
* build: Upgrade qunit from 2.20.0 to 2.20.1
* build: Upgrade eslint-config-wikimedia from 0.26.0 to 0.27.0

Bump browserslist-config-wikimedia and postcss-html dependencies

---

package.json
src/utils.js
support-basic-rules.js
support-modern-rules.js
test/fixtures/basic/invalid.less
test/fixtures/modern/invalid.less

Ignore 'css-nesting' errors in LESS files
