wikimedia/stylelint-config-wikimedia

index.js

Fixing `value-list-comma-newline-before` to `never-multi-line` as well.

Fix `value-list-comma-newline-before`

---

index.js

Set selector-pseudo-element-colon-notation to single

---

index.js

Per CSS coding conventions:
OK:
* 0
* 30px
* 2.2em
* 0.5rem
Bad:
* .3px
* 0em
* 0.20rem
Fixes #1.

Require leading, no trailing, and unitless zeros

---

CHANGELOG.md
package.json

Changes:
* New rule: `number-leading-zero`, configured as 'always' (James D. Forrester)
* New rule: `number-no-trailing-zeros`, configured as 'true' (James D. Forrester)
* New rule: `number-zero-length-no-unit`, configured as 'true' (James D. Forrester)
* New rule: `stylelint-value-border-zero` (via plugin), configured as '0' (Volker E.)
* Change rule: Set `selector-pseudo-element-colon-notation` to 'single', not 'double' (Ed Sanders)
* Change rule: Set `value-list-comma-newline-before` to 'never-multi-line', not 'always-multi-line' (Volker E.)
* build: Provide a .jscsrc file for local JavaScript linting (James D. Forrester)

Tag v0.2.0

---

index.js

Adding `outline: none` to declaration-property-value-blacklist.
Fixing #21

Add outline to property value blacklist

---

index.js

Reordering stylelint rules for better scan-ability in alphabetical order with exceptions for special 
Wikimedia Foundation whitespace treatment.
Issue: #5

Reorder stylelint rules

---

index.js

For some reason we had it twice.
Part of #42.

Removed rule: `selector-root-no-composition` is deprecated

---

index.js

The option `blockless-group` is now called `blockless-after-blockless`.
Part of #42.

Updated rule: `at-rule-empty-line-before` option renamed

---

index.js

Replaced instead with `block-closing-brace-newline-after` and `block-closing-brace-newline-before` set to "always" (previously "always-multi-line" and unset, respectively).
Part of #42.

Update rule: `block-no-single-line` is deprecated

---

index.js

Removing unnecessarily duplicated `"selector-pseudo-element-colon-notation": [ "single" ]` rule.

Remove duplicated rule

---

index.js

Ignoring proprietary Microsoft filters `DXImageTransform.Microsoft.*`
in `function-name-case` rule. Follow-up to #3.

Improve `function-name-case` to ignore proprietary MS filters

---

index.js

We use spaces inside all types of brackets: ()[]{} across JS & CSS style guides.
Fixes #49.

Set selector-attribute-brackets-space-inside to always

---

index.js

Part of 'stylelint-config-standard' and a useful addition.

New rule: `block-closing-brace-empty-line-before`, set to `never`

---

index.js

New rule: `comment-whitespace-inside`, set to `always`

---

index.js

…true`
Not setting a generic `font-family` can result in unintended layout
issues across platforms.
Part of #3

New rule: `font-family-no-missing-generic-family-keyword`, set to `true`

---

index.js

Another missing rule, that is already part of our coding guidelines,
but hasn't been integrated into our stylelint config.

New rule: `selector-max-empty-lines`, set to `0`

---

index.js

Adding exception for 'first-nested' and ignoring 'after-comment'.
Fixes #76

New rule 'rule-empty-line-before', set to 'always-multi-line'

---

index.js

Bringing consistency to the syntax by standardizing on
non-array single values for better readability.

Hygiene: Remove array syntax on single values

---

index.js

`rem` with our base font variety doesn't make sense in majority
of our current use cases and is most-often only added by
accident or lack of knowledge.
Fixes #94

New rule: Add `rem` to `unit-blacklist`

---

.github/workflows/irc.yml

We don't use Freenode any more.

CI: Switch IRC network to Libera.Chat

---

grade-a.json
grade-c.json
package.json

This avoids making the next release a breaking change.

Restore grade-a/c as deprecated aliases of support-modern/basic

---

index.js
package-lock.json
package.json

_Edits from @Volker-E 2022-01-03: _
Also adding necessary for v14 'postcss-less' package as custom syntax and define it
as override for Less files.
Let's start with https://stylelint.io/migration-guide/to-14
- Mainly new dependency for custom syntax in v14+ 'postcss-less' above. 
- Wikimedia Deutschland might consider 'postcss-scss' for their projects, stylelint even provides a https://github.com/stylelint-scss/stylelint-config-recommended-scss package.
- No removals are affecting us. 
https://github.com/stylelint/stylelint/blob/main/CHANGELOG.md#1420 shows the other additional features. We can add them in following patches if useful.
**14.2.0**
- Nothing added.
**14.1.0**
- Added: rule-selector-property-disallowed-list rule (#5679).
- Added: ignore: …

Require stylelint 14.2.0, up from 13.13.1

---

.gitignore
package-lock.json
package.json

This is in response to stylelint 14 dropping it.
Fixes #153.

Add postcss-less as a dependency

---

CHANGELOG.md

No-op changes to library functionality just clutter the list

Remove dev-only changes from CHANGELOG.md

---

index.js
package-lock.json
package.json
test/fixtures/default/invalid.css
test/index.js

Introduces the following rules:
* custom-property-no-missing-var-function
* declaration-block-no-duplicate-custom-properties
* font-family-no-duplicate-names
* keyframe-declaration-no-important
* named-grid-areas-no-invalid
* no-duplicate-at-import-rules
* no-empty-source
* no-invalid-position-at-import-rule
* no-irregular-whitespace
* selector-pseudo-element-no-unknown
Remove rules which are duplicated upstream
declaration-block-no-duplicate-properties is changed slightly
from ignore:consecutive-duplicates to
ignore:consecutive-duplicates-with-different-values.
Fixes #173

Extend stylelint-config-recommended

---

package-lock.json
package.json
support-basic.js
support-modern.js
test/fixtures/basic/invalid.css
test/fixtures/basic/valid.css
test/fixtures/default/invalid.css
test/fixtures/modern/invalid.css
test/fixtures/modern/valid.css

- Update Stylelint to 14.8.1
- Update stylelint-config-recommended to 7.0.0
- Basic/modern: Set `selector-not-notation` to `simple`

Update Stylelint and stylelint-config-recommended

---

index.js

Now that we have dropped support for IE<11, we shouldn't need these
old filter hacks.

Changed rule: `function-name-case`: Remove exception for 'DXImageTransform.Microsoft'

---

README.md
index.js
mediawiki.js
package.json
support-basic.js
test/fixtures/default/invalid.css
test/fixtures/mediawiki/.stylelintrc.json
test/fixtures/mediawiki/invalid.css
test/fixtures/mediawiki/invalid.less
test/fixtures/mediawiki/valid.css
test/fixtures/mediawiki/valid.less

* Introduce `mediawiki` config
* New rule: `selector-class-pattern`, to prevent use of overly-generic class names without prefixes
Fixes #182, #86

mediawiki config and selector-class-pattern

---

index.js
mediawiki.js
test/fixtures/default/valid.less
test/fixtures/mediawiki/valid.less

Any environment using LESS, not just MediaWiki environments, will
allow @import anywhere in the file.

Move `no-invalid-position-at-import-rule` from mediawiki to index

---

rules/no-at-import-css.js
test/fixtures/mediawiki/invalid.less
test/fixtures/mediawiki/valid.less

This option does not tell LESS not to handle the import, it tells
LESS to inline the whole file verbatim when importing. It allows
CSS files to be imported by the LESS processor, and should be
considered valid.

Rule fix: Handle (inline) properly in `no-at-import-css`

---

package-lock.json
package.json
test/fixtures/default/invalid.css

stylelint                                   14.9.1  →  14.16.1
stylelint-config-recommended                 8.0.0  →    9.0.0
stylelint-no-unsupported-browser-features    5.0.3  →    6.0.1
Fix #198

build: Update 'stylelint' and dependencies to latest

---

index.js
test/fixtures/default/invalid.css

To follow CSS standard and not outdated browsers.
Fix #200

Changed rule: `selector-pseudo-element-colon-notation`: Expect double colon notation not single

---

mediawiki.js
test/fixtures/mediawiki/valid.vue

at-rule-disallowed-list was forbidding all uses of @import in .vue files, even the ones that we want to allow.

mediawiki: Allow @import in Less in .vue files too

---

index.js
test/fixtures/default/invalid.css

We no longer support browsers that don't understand rems at all.
Related to #98

Dropped rule: `unit-disallowed-list`, allow `rem` units from now on.

---

package-lock.json
package.json
test/fixtures/basic/invalid.css
test/fixtures/basic/valid.css
test/fixtures/modern/invalid.css
test/fixtures/modern/valid.css

Due to an upstream bug in doiuse (https://github.com/anandthakker/doiuse/issues/168)
we can't deploy this.

Downgrade stylelint-no-unsupported-browser-features to 6.1.0

---

test/index.js

Valid fixtures should contain only valid code. Adding an inline
disable should never be allowed.

Assert that valid fixtures contain no disables

---

index.js
test/fixtures/default/valid.css

This requires a fairly modern browser version (after 2020) and
we don't reliable know if CSS needs to run on "basic" browsers.

Don't suggest the 'inset' shorthand for top/right/bottom/left

---

.github/workflows/nodejs.yml
README.md
index.js
package-lock.json
package.json
support-basic-rules.js
test/fixtures/default/invalid.css
test/fixtures/default/invalid.windows.css
test/fixtures/default/valid.css
test/fixtures/default/valid.less
test/fixtures/default/valid.vue
test/index.js

Also
- changing to '@stylistic/stylelint-plugin' as 'stylelint-stylistic' isn't compatible with Stylelint 16 anymore
- removing Node 16 from the CI as it's not supported by Stylelint 16
Fixes #10

build: Upgrade to Stylelint 16

---

package-lock.json
package.json
test/fixtures/default/invalid.css

With Stylelint 16.7.0 we made some fixes to `declaration-block-no-duplicate-properties` which requires moving the disable comments.

Upgrade stylelint from 16.2.0 to 16.7.0
